如何理解

> 对于非线程所有者的代码来说(例如:对于线程池而言,任何在线程池实现以外的代码)中都应该小心地保存中断状态

首先贴一个demo, 线程的所有者实际上是ExecutorService的实例对象executor, 而非线程所有者, 或者说我理解成任务代码就是Task的Run方法块.

```java
public class InterruptedTest {
    public static void main(String[] args) throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(5);
        // 提交任务并获取Future对象
        Future<?> future = executor.submit(new Task());
        Thread.sleep(100);
        // 取消任务
        future.cancel(true);
        Thread.sleep(1000);

        // 关闭线程池
        executor.shutdown();
    }
    static class Task implements Runnable {
        @Override
        public void run() {
            try {
                // 模拟耗时操作
                Thread.sleep(2000);
                System.out.println("任务完成");
            } catch (InterruptedException e) {
                System.out.println("任务被中断");
                Thread thread = Thread.currentThread();
                System.out.println("是否被打断 " + thread.isInterrupted());
                Thread.currentThread().interrupt();
                System.out.println("是否被打断 " + thread.isInterrupted());
            }
        }
    }
}
```

在将Task实例提交到线程池后, 会获得一个Future类型的实例对象, 执行逻辑就不再多说. 重点是执行Future实例的cancel方法后会发生什么, 以及在执行线程池的shutdown方法时会发生什么

首先先贴上Future的cancel方法源码

```java
// 如果 mayInterruptIfRunning 参数为 true，则尝试中断任务的执行线程
public boolean cancel(boolean mayInterruptIfRunning) {
    	// 判断future对象的状态 以及CAS设置对象的状态
        if (!(state == NEW &&
              UNSAFE.compareAndSwapInt(this, stateOffset, NEW,
                  mayInterruptIfRunning ? INTERRUPTING : CANCELLED)))
            return false;
        try {    // in case call to interrupt throws exception
            if (mayInterruptIfRunning) {
                try {
                    Thread t = runner;
                    if (t != null)
                        // 这里中断线程池中的执行线程
                        t.interrupt();
                } finally { // final state
                    UNSAFE.putOrderedInt(this, stateOffset, INTERRUPTED);
                }
            }
        } finally {
            finishCompletion();
        }
        return true;
    }
```

通过源码我们可以看到,  在demo中执行future.cancel(true)方法时,会去调用线程的interrupt方法, 也就会触发Task的Run方法中的catch代码块

这里我们分两种情况来分析

1. 捕获InterruptedException异常但不复位

   在线程池执行shutdown方法时, 线程池还会去执行对应线程的interrupt方法, 虽然不会有额外的效果

2. 捕获InterruptedException异常且复位

   复位后的线程执行完当前任务后, 在获取下一个任务时也就是线程池执行runWork方法时, 会调用Thread.interrupted方法, 测试当前线程是否被中断（检查中断标志），返回一个boolean并清除中断状态. 这同时也就对应了只有线程的拥有者才可以处理的中断状态.

这一步需要贴上ExecutorServiced的shutdown方法源码

```java
private void interruptIdleWorkers(boolean onlyOne) {
        final ReentrantLock mainLock = this.mainLock;
        mainLock.lock();
        try {
            for (Worker w : workers) {
                Thread t = w.thread;
                if (!t.isInterrupted() && w.tryLock()) {
                    try {
                        t.interrupt();
                    } catch (SecurityException ignore) {
                    } finally {
                        w.unlock();
                    }
                }
                if (onlyOne)
                    break;
            }
        } finally {
            mainLock.unlock();
        }
    }
```

